var app = new Vue({
    el:'#app',
    data:{
        arr:[
            {
                href:'./html/single.html',
                src:'./images/work_1.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_2.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_3.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_4.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_5.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_6.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_7.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_8.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_9.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_10.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_11.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_12.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_13.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_14.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_15.jpg',
                title:'标题',
                subtitle:'副标题'
            },
            {
                href:'./html/single.html',
                src:'./images/work_16.jpg',
                title:'标题',
                subtitle:'副标题'
            },
        ]
    }
})
var app1 = new Vue({
    el:'#app1',
    data:{
        list:[
            {
                class:'icon-search',
                title:'标题',
                text:'正文'
            },
            {
                class:'icon-search',
                title:'标题',
                text:'正文'
            },
            {
                class:'icon-search',
                title:'标题',
                text:'正文'
            },
            {
                class:'icon-search',
                title:'标题',
                text:'正文'
            }
        ]
    }
})
var app2 = new Vue({
    el:'#app2',
    data:{
        array:[
            {
                src:'images/testimonial_person2.jpg',
                text:'正文',
                author:'作者'
            },{
                src:'images/testimonial_person2.jpg',
                text:'正文',
                author:'作者'
            },{
                src:'images/testimonial_person2.jpg',
                text:'正文',
                author:'作者'
            }
        ]
    }
})
var app3 = new Vue({
    el:'#app3',
    data:{
        list:[
            {
                from:0,
                to:100,
                id:'类型'
            },{
                from:0,
                to:100,
                id:'类型'
            },{
                from:0,
                to:100,
                id:'类型'
            }
        ]
    }
})
var app4 = new Vue({
    el:'#app4',
    data:{
        list:[
            {
                src:'images/person3.jpg',
                title:'标题',
                subtitle:'副标题',
                text:'正文'
            },
            {
                src:'images/person3.jpg',
                title:'标题',
                subtitle:'副标题',
                text:'正文'
            },
            {
                src:'images/person3.jpg',
                title:'标题',
                subtitle:'副标题',
                text:'正文'
            }
        ]
    }
})
var app5 = new Vue({
    el:'#app5',
    data:{
        lists:[
            {
                src:'images/img_1.jpg',
                title:'标题',
                subtitle:'正文1',
                text:'正文2'
            },
            {
                src:'images/img_1.jpg',
                title:'标题',
                subtitle:'正文1',
                text:'正文2'
            },
            {
                src:'images/img_1.jpg',
                title:'标题',
                subtitle:'正文1',
                text:'正文2'
            },
            {
                src:'images/img_1.jpg',
                title:'标题',
                subtitle:'正文1',
                text:'正文2'
            }
        ]
    }
})